version: '3.9'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map cổng 80 trong container thành cổng 8080 trên máy host
    depends_on:
      - server
    networks:
      - job_manager_network

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:80"  # Map cổng 80 trong container thành cổng 5000 trên máy host
    depends_on:
      - sqlserver
    networks:
      - job_manager_network

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "FPTUniversity@123"  # Thay đổi mật khẩu tùy ý
      ACCEPT_EULA: "Y"
    ports:
      - "1443:1433"  # Map cổng 1433 trong container thành cổng 1433 trên máy host
    networks:
      - job_manager_network
    volumes:  # Add a named volume for the database data
      - sqlserver_data:/var/opt/mssql

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"  # Map cổng 80 trong container thành cổng 80 trên máy host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx configuration
    depends_on:
      - client
    networks:
      - job_manager_network

networks:
  job_manager_network:
    driver: bridge

volumes:  # Define the named volume
  sqlserver_data: